version: '2.4'
services:
  {service}.e2e_base:
    command:
      --certs ${SERVICE_HOSTNAME}-joined.pem
      --headless
      --intercept
      --lifecycle-hooks-path lifecycle_hooks.py
      --proxy-mode reverse:${SERVICE_SCHEME}://${SERVICE_HOSTNAME}
      --proxy-port ${SERVICE_PORT}
      --response-fixtures-path fixtures.yml
      --ssl-insecure
    extends:
      service: {service}.proxy_base
    hostname: ${SERVICE_HOSTNAME}
  {service}.proxy_base:
    build:
      args:
        HOSTNAME: ${SERVICE_HOSTNAME}
      dockerfile: ./Dockerfile.proxy
    extends:
      file: ../docker-compose.base.yml
      service: proxy_base
  {service}.mock_base:
    command: 
      --certs ${SERVICE_HOSTNAME}-joined.pem
      --headless
      --lifecycle-hooks-path lifecycle_hooks.py
      --proxy-mode reverse:${SERVICE_SCHEME}://${SERVICE_HOSTNAME}
      --proxy-port ${SERVICE_PORT}
      --ssl-insecure
    extends:
      service: {service}.proxy_base
  # Builds mocks from snapshots
  {service}.build_base:
    entrypoint: ['bin/apply']
    extends:
      service: {service}.proxy_base
  # Configures record and mock settings
  {service}.configure_base:
    entrypoint: ['bin/configure', '${SERVICE_SCHEME}://${SERVICE_HOSTNAME}']
    extends:
      service: {service}.proxy_base