version: '2.4'
services:
  gateway:
    extends:
      file: ../docker-compose.base.yml
      service: gateway_base
    profiles:
      - e2e
networks:
  gateway:
    name: ${NETWORK}
    external: true
