version: '2.4'
services:
  {service}.{workflow}.configure:
    build:
      dockerfile: ../Dockerfile.sidecar
    extends:
      file: ../docker-compose.base.yml
      service: proxy_configure_base
    profiles:
      - e2e
